### ISSUE TITLE
prohibit double inheritance?

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#1012]
```
ex_double_inheritance is
  a is

  b : a, a is
```

seems like bad style, at least. the compiler should report an error or a warning, in my opinion.

**Comment by fridis** [comment]
This happens often and is even useful. With renaming (which is still missing), we can do this
```
  a is
    x => "a.x"
  b is : 
    a,
    a rename x as original_x
  redef x => original_x; say "b.x"
```
we can have a counterpart to Java's `super.x()`. 
Also, we could do things like defining a ring with `e` and `infix °`, and then define a field that inherits twice renaming these operations as `zero`/`infix +` and `one`/`infix *`.
Related is the classical route-inheritance, which implicitly inherits repeatedly: 
```
a is
b : a is
c : a is
d : b, c is
```
A feature `x` defined in `a` is inherited twice here, which might be redefined in `b` and `c`, while `d` might want to keep both versions or redefine them by one common implementation or redefine both into two new features (requiring renaming again). 
This whole thing becomes real fun if `a` has type parameters and `b` and `c` provide incompatible actual type parameters. This leads to cases that are not well defined in Fuzion yet, we need renaming here to distinguish repeatedly inherited features that became incompatible due to incompatible actual type parameters in the inheritance call.
