### ISSUE TITLE
no error even for redefinition

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#1085]
This produces an error:
```
ex =>
  a(T type) is
  c(T type) : a T is
```
while this does not:
```
ex =>
  a(T type) is
  b(T type) is
    c : a T is
```

**Comment by fridis** [comment]
I do not see the problem here, what kind of error do you expect? 
In case `T` is used within `ex.b.c`, there are two possible type parameters that match: the inherited `ex.a.T` and the outer `ex.b.T`. This ambiguity exists as well for features that are not type-parameters and it is resolved by giving preference to the inherited one (I think:-). 

We need to formally document this at some point. We could also produce an error or a warning and we might want to provide syntax to allow selecting a specific `T`, e.g., `ex.b.this.T` for the outer one vs. `ex.b.c.this.T` or just `T` for the inherited one.
