### ISSUE TITLE
replace `c_string` in stdlib by array and length

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#1143]
Right there are two ways how we pass strings in intrinsics.
One is passing an array and a length separately as in `fuzion.sys.out.write`, number two is passing a null terminated array as in `fuzion.sys.env_vars.has0`. We should use only one mechanism.

**Comment by fridis** [comment]
The reason for this is to avoid additional allocations in the C backend.  This was explained in #1181: _I prefer not to add additional allocation of C strings at this point since this would make the implementation of a future GC more complicated. We might revisit this once we have a GC and we see that the string copying is a performance issue._

I will close this for now, we might reconsider this once the C backend has evolved further and we have our own GC implementation.
