### ISSUE TITLE
expressions exceeding one line

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#130]
Currently expressions may not exceed one line except when wrapped with parentheses. 
Users probably expect this to parse though:
```
ex is
  a := 1 * (2
    + 3
    + 4) - 5
```
> example.fz:4:10: error 1: Syntax error: expected semicolon ';', found operator '-'
    + 4) - 5

**Comment by fridis** [comment]
This is intentional. If an expression exceeds one line, the whole expression has to be wrapped in parentheses. Parsing of the expression stops after ')' since the following tokens are in a different line than the start of the expression. For Fuzion, a newline basically has the same role as a semicolon, this is why the error message says it expects a semicolon here. 
I leave this issue open since the error message could be improved: 
- it should say that a newline or a semicolon was expected
- it should explain that wrapping the whole expression in parentheses would solve this
