### ISSUE TITLE
question: remove `tuple`?

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#1912]
Considering it is so easy to define a feature now, e.g. using free types what is the use for tuples?
Should we remove those? I don't see much value using them. Expect for them making code harder to read...

**Comment by fridis** [comment]
It is good to question any potential freight we added to the language. Tuple is the type of an expression like `(a,b,c)`. I think it is good to have a default tuple type instead of requiring the definition of a type for each use, like in `zip` or whenever a function returns more than one value, but feel free to experiment with alternatives.
