### ISSUE TITLE
What about Ada?

### ISSUE THREAD

**Issue by TamaMcGlinn** [tokiwa-software/fuzion#21]
Since you had a poster session at AdaEurope last week, we can assume you are aware of the strengths of the Ada programming language (simplicity, abstraction, consistency, safety, scalability, efficiency, extensibility, interoperability, analyzability and determinism). However, [the purpose page](https://flang.dev/purpose) names a couple of programming languages, but not Ada.

Fuzion has advantages, of course. I am not saying 'stop, Ada has all this' - because it doesn't, of course. Ada has legacy which means it can't move in certain directions, and certainly not as quickly as a new language. But the question is, does Fuzion also have all the advantages of Ada? We don't want a new language to be a step back in other areas which are already long solved, so I hope you will consider this:

# Ranges on types

An aspect of safety and abstraction in the Ada language lies in the compiler's choice of the bit-representation;

```ada
type Buttons_On_Coat is range 1 .. 100;
```

Choosing the number of bits is an implementation detail, which the programmer might get wrong. So in Ada, the compiler chooses it correctly by default. If it is not possible (because the range is too big), a compile error is given. However, the programmer may specify some aspects; for instance, the underlying representation of the values, or the size of the type in bits, or both; but again, if the programmers gets these wrong, the compiler emits an error.

This also makes it impossible to confuse `Buttons_On_Coat` with other 'integerish' types.

The point is even more important for Real (i.e. non-integer) types, because there are so many more points of choice - do you want floating or fixed point? What's the range and precision required? Is the closest power-of-two for the precision good enough, since it gives a lot more speed on floating point hardware? In C++, for instance, you technically can do all this by making your own templated type, but considering the difficulty of writing template code in C++, it is doubtful that many of those implementations are correct.

In Ada, you simply state your answer to these questions, and the compiler provides you with the necessary conversions e.g. if you cast a fixed point decimal Real precise to 0.01 to Integer, it will multiply by 100 to get what you need, but this is abstracted away:

```ada
with Ada.Text_IO; use Ada.Text_IO;

procedure Main is
   type Money is delta 0.01 range -9_999.99 .. 9_999.99 with
      Small => 0.01;
   M : constant Money   := 550.49;
   I : constant Integer := Integer (M);
begin
   Put_Line (I'Image);
end Main;
```

Since compilers must satisfy [ACATS](http://www.ada-auth.org/acats.html), they have to get this right, and users don't have to.

# Access (pointer) scope

In Ada, it is not permitted to store a pointer/reference/access/whatchamathingy to a variable which is out-of-scope. This program fails to compile with `main.adb:9:17: error: non-local pointer cannot point to local object`, although changing `'Access` to `'Unchecked_Access` overrides that and still does not print 42:

```ada
with Ada.Text_IO; use Ada.Text_IO;

procedure Main is
   Get_It : access Integer;
begin
   declare
      It : aliased Integer := 42;
      -- this is where we should declare Get_It
   begin
      Get_It := It'Access;
      -- this is where we should print it
   end;
   Put_Line (Get_It.all'Image);
end Main;
```

**Comment by fridis** [comment]
Thank you for the good input. I am happy to learn from other languages and to steal good ideas, but I am trying to do this in a way that adds as little complexity as possible to the Fuzion language itself. 

It is right that Ada is not mentioned on the flang.dev website. This is just because until recently, there was no direct influence from Ada to Fuzion. My experience working on an Ada compiler dates back to a student project in the 90's. Additions to Ada such as pre- and postconditions influenced Fuzion indirectly, e.g. via the Java Modeling Language JML or Java specifications like RTSJ ans SC-Java, that are themselves influenced by Ravenscar Ada. 

Fuzion, at the moment, is a mere proof-of-concept, so it has many disadvantages compared to Ada which has industrial strength implementations and accompanying tools. 

# Ranges 

Choosing integer types with the minimum number of bits is not what is supported by Fuzion at this point. I have not even decided on what the algorithm should be to decide the type of an integer literal such as `123`. Should this be u8, or i8, or i32 (as it is right now)?

Your example definition of type Money is something that I probably would not make part of the Fuzion language at all. To me, this kind of detailed control should be part of some a library that provides support for fixed-point integer values. The task of the language and the compiler should be to provide no obstacles to make such a library operate at high performance as if the compiler would support this directly. What can be done already in Fuzion is wrapping, e.g., an i64 integer, into some other type without additional overead. Applied to your example, we could, e.g., define

```
  myRangeType<T: integer<T>> (min, max T) is
    amount (val T) 
       pre
          debug: min <= val <= max
    is
      ...
```

so you could do 

```
  money := myRangeType 9_999, +9_999
  m := money.amount 555
  say m.val
```
and working with values would create no runtime overhead compared to plain integer values unless debugging is enabled. 

In this example, the generic type `T` is inferred form the arguments to `myRangeType`. The compiler should remove all fields from `myRangeType` (since their values are compile time constants and, if debug is disabled, never even read), so myRangeType becomes a unit type that generates no code at all. money.amount would hence just create a wrapped `i32`.

But many things still need to be improved: the cryptic `<T>` generic argument to `integer` should not be needed (using Eiffel-style `like this` within the implementation of `integer` instead), better support for currying could allow to avoid the declaration of `amount` as inner feature (such that `money.amount 555` in my example would become `money 555`), etc. 

In any case, the compiler should stay simple, but provide mechanisms and optimizations generic enough to do powerful things efficiently in the library. 

# Pointers

Fuzion does not allow to take the address of any field and to pass it as a result. However, one can create closures that would allow accessing a field declared locally to a feature after the call to that declaring feature has returned. In this case, the compiler will detect that the field will have to reside in a heap allocated area reachable from the closure that is returned. And a GC will eventually reclaim the memory if static analysis cannot detect that the scope is limited to one of the callers.

**Comment by TamaMcGlinn** [comment]
In C++, we endlessly argue about whether to use `0L`, `0LL` or `0ULL` even though zero is zero.

An integer literal, like a constant, should not itself need a specific type, since it cannot be used directly, and it is too early to determine what trade-off to make between range and precision. Instead, the type should be determined at the point in the program where it is written into a variable, or passed as an actual argument. In the below, I have one definition of the `Something` numerical constant, but the binary which the compiler has to write for me will have 3 with different representations, because the variables being assigned to are specifying different choices regarding range and precision, which require different representations.

```
with Ada.Text_IO;

procedure hello is
   Something : constant := 8.283873489237984729834729379234;
   type Small_Fixed is delta 0.01 range 0.00 .. 1_000_000.00
      with Small => 0.01;
   S : Small_Fixed := Something;
   T : Small_Fixed := 9.23487; -- gives a warning, 487 is ignored
   type Large_Fixed is delta 0.0000001 range 0.0000000 .. 10.0000000;
   More_Fixed : Large_Fixed := Something;
   type Large_Float is digits 10 range -9.0 .. 9.0;
   More_Floating : Large_Float := Something;
begin
   Ada.Text_IO.Put_Line ("S =" & S'Image);
   Ada.Text_IO.Put_Line ("T =" & T'Image);
   Ada.Text_IO.Put_Line ("More_Fixed =" & More_Fixed'Image);
   Ada.Text_IO.Put_Line ("More_Floating =" & More_Floating'Image);
end hello;
```

prints:
```
S = 8.28
T = 9.23
More_Fixed = 8.2838734
More_Floating = 8.283873489E+00
```

This is the reason why C++ has many definitions for each numerical constant, but Ada has a single Math.Pi definition that can be reused in all calculations.

**Comment by fridis** [comment]
Thank you for the insights into constants in Ada. An interesting approach. A little surprising to me is that assigning 'Something' to S in your example apparently is accepted by the compiler, while '9.23487' causes a warning. So losing precision is tolerated in some cases. 

In Fuzion, numeric literals like '1' or '3.14' do not have a type, but once they are assigned to a feature, that feature has a type, either given explicitly or inferred from the literal assigned to it. 
To achieve a behavior like in Ada, the inferred type for a constant like PI must be infinitely accurate, and implicit, compile-time conversions to types with restricted accuracy should occur when this type is assigned or used otherwise. 

Anyway, all this input helps me to decide on a good approach for Fuzion.

**Comment by TamaMcGlinn** [comment]
I think it makes sense; since '9.23487' is a literal, the programmer has clearly made some sort of judgement error in writing out more decimals than are actually stored. When assigning Something, which is a named constant, we can't complain because that can be re-used elsewhere (even possibly some in other programs which the compiler cannot see right now) and maybe those other places use the rest of the digits.

Rather than saying the constant is 'infinitely accurate', it might be better to think of it as deferring the choice of bitrepresentation until a non-constant gets the value. I wonder how this works though, when you expose a constant in the public part of your package, and then link dynamically? Maybe Ada actually does choose a 'maximum accuracy' for constants in this case?

**Comment by fridis** [comment]
I will close this issue for now. The support floats with user defined precision as in Ada is IMHO nothing that should go into the Fuzion language, but an idea that might be implemented in a specific library supporting floats of a specific precision. Then, if this turns out to require help by the compiler to achieve good performance, this might lead to new optimizations being introduced into the compiler, preferably generic ones that also improve other code.
