### ISSUE TITLE
changing mutable in feature

### ISSUE THREAD

**Issue by michaellilltokiwa** [tokiwa-software/fuzion#341]
I'm unsure if this is a bug or if it is intended behavior. Either way it surprised me.
@fridis  Maybe you can share your thoughts on this?

Example:
```fuzion
ex =>
  i := mut 0

  increment(x ref mutate.new i32) is
    x <- x.get + 1

  increment i

  say i.get

  i <- i.get + 1

  say i.get
```
Output:
```
0
1
```

**Comment by fridis** [comment]
The issue is that `i` is a value type. When passed to a `ref` as in `increment i`, this value is copied into a newly created `ref` instance, so the original `i` is not changed. 
Here is the same example that works, we must declare `i ` as a ref in the first place: 
```
ex =>
  i ref mutate.new i32 := mut 0

  increment(x ref mutate.new i32) is
    x <- x.get + 1

  increment i

  say i.get

  i <- i.get + 1

  say i.get
```
gives
```
 > ./build/bin/fz ex_341a.fz 
1
2
```
I am thinking of adding a `ref` operator such that you could write 
```
  i := ref mut 0
```
instead. This would also enhance the duality of types and expressions, so `ref T` is the reference type to a value of type `T` while `ref v` is a reference to a copy of the value `v`.
Will create a new issue for this.

**Comment by michaellilltokiwa** [comment]
superseded by #1219
