### ISSUE TITLE
references to features in docs: in quotes or not?

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#788]
from `lib/Sequence.fz`:
```
# Sequence -- ancestor for features that can be converted to a 'list' or a
# 'stream'
#
# Sequences are empty, finite or infinite ordered collections of instances
# of a given type.  Sequences may calculate elements lazily on demand.
#
# Sequence is a 'ref' type, i.e., different sub-features may be assigned
# to a field of type 'Sequence'.
#
# Heirs of Sequence must implement either 'asList' or 'asStream'.  Failure
# to implement any of these results in an endless recursion when the Sequence
# is used.
#
```

I would prefer to just remove the quotes. What do you think @fridis @michaellilltokiwa ?

**Comment by michaellilltokiwa** [comment]
I agree, they are not helpful. We could also replace them by back ticks then use `<code>` to render them in fzdocs.

**Comment by fridis** [comment]
There are many cases where it is easy to confuse feature names with English text, so we need some way to distinguish those. But then we should stay consistent and do it the same way throughout. 

I am not a big fan of back ticks, but this is the standard in markup, so we should probably use it instead of the normal ticks I used throughout. 

In a next step, some form of markup support for `fzdoc` would be great...:-)
