### ISSUE TITLE
compiler no longer warns about all missing intrinsics

### ISSUE THREAD

**Issue by maxteufel** [tokiwa-software/fuzion#963]
In flang.dev `content/design/examples/arg_intri.fz` with the C backend:

```diff
@@ -1,5 +1,8 @@
-warning 1: code for intrinsic arg_intri.foo is missing
-warning 2: code for intrinsic arg_intri.foo2 is missing
-warning 3: code for intrinsic arg_intri.foo3 is missing
-3 warnings.
+
+warning 1: DFA: code to handle intrinsic 'arg_intri.foo' is missing
+
+
+warning 2: code for intrinsic arg_intri.foo is missing
+
+2 warnings.
 *** error: NYI: code for intrinsic arg_intri.foo is missing
```

is this intended or a bug?

(edit: also happens in `content/design/examples/red_intri.fz`, `content/design/examples/tya_intri.fz`)

**Comment by fridis** [comment]
This should be ok, the DFA and the compiler only report what is reachable. You can provoke `foo2` to be shown by adding an ìf` before the call of `foo`, e.g.:
```
   if (time.nano.read = 3) say (foo 42 9999999.as_u64 true)
```
and there should be no way to get the warning for `foo3` since it is absurd. 
What we should maybe improve is reducing the number of empty lines around the warnings.
